import os
from reportlab.pdfgen import canvas
from pypdf import PdfReader, PdfWriter
import tempfile


from utils.constants import *
from utils.template_loader import load_template
from utils.template_engine import TemplateEngine

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def generate_pdf(
    images,
    company_name,
    website,
    logo_path,
    template_name,
    custom_background,
    images_per_page,
    output_path,
):

    # ------------------------------------------
    # Create PDF
    # ------------------------------------------

    c = canvas.Canvas(

        output_path,

        pagesize=(PAGE_WIDTH, PAGE_HEIGHT)

    )

    # ------------------------------------------
    # Load Selected Template
    # ------------------------------------------

    if template_name == "custom":
    
        # Use an existing template as the base layout
        template = load_template("minimal")

    else:

        template = load_template(template_name)

    if template is None:
        raise Exception(f"Template '{template_name}' could not be loaded.")

    if custom_background:
        template["background"] = custom_background

    engine = TemplateEngine(

        c,

        template

    )
    
    # ------------------------------------------
    # Fixed Cover Page (Page 1)
    # ------------------------------------------
    c.drawImage(
        "assets/cover_page1.png",
        0,
        0,
        width=PAGE_WIDTH,
        height=PAGE_HEIGHT
    )
    
    c.showPage()
    
    # ------------------------------------------
    # Fixed Intro Page (Page 2)
    # ------------------------------------------
    c.drawImage(
        "assets/cover_page2.png",
        0,
        0,
        width=PAGE_WIDTH,
        height=PAGE_HEIGHT
    )
    c.showPage()
    
    total_images = len(images)

    page_number = 1

    # ------------------------------------------
    # Generate Pages
    # ------------------------------------------

    for start in range(

        0,

        total_images,

        images_per_page

    ):

        page_images = images[

            start:start + images_per_page

        ]

        # --------------------------------------
        # Background
        # --------------------------------------

        engine.draw_background(

            PAGE_WIDTH,

            PAGE_HEIGHT,

            

        )

        # --------------------------------------
        # Logo
        # --------------------------------------

        engine.draw_logo(

            logo_path

        )

        # --------------------------------------
        # Company Name
        # --------------------------------------

        engine.draw_company(

            company_name

        )

        # --------------------------------------
        # Website
        # --------------------------------------

        engine.draw_website(

            website

        )

        # --------------------------------------
        # Product Images
        # --------------------------------------

        engine.draw_images(

            page_images,

            images_per_page

        )

        # --------------------------------------
        # Footer
        # --------------------------------------

        #FOOTER_TEXT = os.getenv(
        #    "FOOTER_TEXT",
         #   "Generated by PDFPlus"
        #)

        #engine.draw_footer(FOOTER_TEXT)

        # --------------------------------------
        # Page Number
        # --------------------------------------

        engine.draw_page_number(

            page_number

        )

        c.showPage()

        page_number += 1

    # ------------------------------------------
    # Save PDF
    # ------------------------------------------

    c.save()
    
    # ------------------------------------------
    # Merge Cover PDF + Generated Catalogue
    # ------------------------------------------

    cover_pdf = os.path.join(
        BASE_DIR,
        "templates",
        "cover",
        "cover.pdf"
    )

    if os.path.exists(cover_pdf):

        writer = PdfWriter()

        # Add cover pages
        cover_reader = PdfReader(cover_pdf)
        for page in cover_reader.pages:
            writer.add_page(page)

        # Add generated catalogue pages
        catalogue_reader = PdfReader(output_path)
        for page in catalogue_reader.pages:
            writer.add_page(page)

        temp_output = output_path + ".tmp"

        with open(temp_output, "wb") as f:
            writer.write(f)

        os.replace(temp_output, output_path)

    return output_path