from reportlab.pdfgen import canvas

from utils.constants import *
from utils.template_loader import load_template
from utils.template_engine import TemplateEngine


def generate_pdf(
    images,
    company_name,
    website,
    logo_path,
    template_name,
    images_per_page,
    output_path,
    custom_background=None
):

    # ------------------------------------------
    # Create PDF
    # ------------------------------------------

    c = canvas.Canvas(

        output_path,

        pagesize=(PAGE_WIDTH, PAGE_HEIGHT)

    )

    # ------------------------------------------
    # Load Selected Template
    # ------------------------------------------

    template = load_template(template_name)

    engine = TemplateEngine(

        c,

        template

    )

    total_images = len(images)

    page_number = 1

    # ------------------------------------------
    # Generate Pages
    # ------------------------------------------

    for start in range(

        0,

        total_images,

        images_per_page

    ):

        page_images = images[

            start:start + images_per_page

        ]

        # --------------------------------------
        # Background
        # --------------------------------------

        engine.draw_background(

            PAGE_WIDTH,

            PAGE_HEIGHT,

            custom_background

        )

        # --------------------------------------
        # Logo
        # --------------------------------------

        engine.draw_logo(

            logo_path

        )

        # --------------------------------------
        # Company Name
        # --------------------------------------

        engine.draw_company(

            company_name

        )

        # --------------------------------------
        # Website
        # --------------------------------------

        engine.draw_website(

            website

        )

        # --------------------------------------
        # Product Images
        # --------------------------------------

        engine.draw_images(

            page_images,

            images_per_page

        )

        # --------------------------------------
        # Footer
        # --------------------------------------

        engine.draw_footer(

            "Generated by PDFPlus"

        )

        # --------------------------------------
        # Page Number
        # --------------------------------------

        engine.draw_page_number(

            page_number

        )

        c.showPage()

        page_number += 1

    # ------------------------------------------
    # Save PDF
    # ------------------------------------------

    c.save()

    return output_path